name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: bun install

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: "chore(release): version package"
          commit: "chore(release): version package"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
